/* SPDX-License-Identifier: GPL-2.0 */
/* GENERATED by tools/harness/export_weights.py --emit-lut.  Do not edit. */
/*
 * Fixed-point sigmoid over the top-1/top-2 margin.  The eBPF
 * verifier forbids floating point, so confidence comes from this
 * table rather than a softmax.  It is a property of the
 * arithmetic, not of the model, which is why it is compiled in
 * rather than shipped in the weight blob.
 */
#ifndef _TX_SIGMOID_LUT_H
#define _TX_SIGMOID_LUT_H

#define TX_SIGMOID_LUT_N 64

static const __u8 tx_sigmoid_lut[TX_SIGMOID_LUT_N] = {
	  0,  16,  32,  48,  63,  78,  93, 106,
	119, 132, 143, 154, 164, 173, 181, 189,
	196, 202, 208, 213, 218, 222, 226, 229,
	232, 235, 237, 239, 241, 242, 244, 245,
	246, 247, 248, 249, 250, 250, 251, 251,
	252, 252, 253, 253, 253, 253, 254, 254,
	254, 254, 254, 254, 254, 254, 254, 255,
	255, 255, 255, 255, 255, 255, 255, 255,
};

#endif /* _TX_SIGMOID_LUT_H */
